---

# [ 6.0 ]
- name: Copy OpenERP configuration file (6.0)
  template: src=openerp-server-v60.conf dest={{ openerp_config_file }}
        owner={{ openerp_user }} group={{ openerp_user }} mode=0600
        force={{ openerp_force_config and 'yes' or 'no' }}
        backup=yes
  when: openerp_version|float == 6.0
# [/ 6.0 ]

# [ 6.1 ]
- name: Copy OpenERP configuration file (6.1)
  template: src=openerp-server-v61.conf dest={{ openerp_config_file }}
        owner={{ openerp_user }} group={{ openerp_user }} mode=0600
        force={{ openerp_force_config and 'yes' or 'no' }}
        backup=yes
  when: openerp_version|float == 6.1
# [/ 6.1 ]

# [ 7.0 ]
- name: Copy OpenERP configuration file (7.0)
  template: src=openerp-server-v70.conf dest={{ openerp_config_file }}
        owner={{ openerp_user }} group={{ openerp_user }} mode=0600
        force={{ openerp_force_config and 'yes' or 'no' }}
        backup=yes
  when: openerp_version|float == 7.0
# [/ 7.0 ]
