---

- include: install.yml
  tags:
    - openerp
    - openerp_install

- include: wkhtmltox.yml
  tags:
    - openerp
    - openerp_wkhtmltox

- include: config.yml
  tags:
    - openerp
    - openerp_config

- include: postgresql.yml
  tags:
    - openerp
    - openerp_postgresql

- include: service.yml
  tags:
    - openerp
    - openerp_service
