---

- name: Detect Debian architecture (i386 or amd64)
  set_fact: openerp_debian_arch={{ '64' in ansible_architecture and 'amd64' or 'i386' }}

- name: Download wkhtmltox
  get_url: url={{ item }}
           dest={{ openerp_wkhtmltox_dest }}
  with_items: "{{ openerp_wkhtmltox_urls }}"
  ignore_errors: True
  when: openerp_wkhtmltox_version is defined and openerp_wkhtmltox_version != False

# Use to detect that the package was downloaded.
# We can not register the result of the previous task to check this as Ansible
# will flag it as failed as soon as one URL fails (even if the download has
# worked on a further URL)
- name: Check wkhtmltox package
  stat: path={{ openerp_wkhtmltox_dest }}
  register: openerp_wkhtmltox_pkg

- name: Install wkhtmltox dependencies
  apt:  pkg={{ item }}
  with_items: "{{ openerp_wkhtmltox_depends }}"
  when: openerp_wkhtmltox_version is defined and openerp_wkhtmltox_version != False and openerp_wkhtmltox_pkg.stat.exists

- name: Install wkhtmltox
  apt:  deb="/root/wkhtmltox-{{ openerp_wkhtmltox_version }}_linux-{{ ansible_distribution_release }}-{{ openerp_debian_arch }}.deb"
        force=yes
  when: openerp_wkhtmltox_version is defined and openerp_wkhtmltox_version != False and openerp_wkhtmltox_pkg.stat.exists
